template: true
valuesFilePath: ./pipelines.values.yml

resources:
  - name: my_repo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.gitRepo.provider }}
      path: {{ .Values.gitRepo.path }}
      branches:
        include: main

  - name: npm_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artiRepo.integration }}

pipelines:
  - name: npm_pipeline
    steps:
      - name: npm_build_step
        type: NpmBuild
        configuration:
          repositoryName: {{ .Values.artiRepo.name }}
          sourceLocation: . 
          integrations:
            - name:  {{ .Values.artiRepo.integration }}
          inputResources:
            - name: my_repo
      - name: npm_test_step
        type: Bash
        configuration:
          sourceLocation: . 
          inputResources:
            - name: my_repo
        execution:
          onExecute:
            - npm run format
            - npm run lint
            - npm run test
      - name: npm_publish_step
        type: NpmPublish
        configuration:
          repositoryName: {{ .Values.artiRepo.name }}
          autoPublishBuildInfo: true
          integrations:
            - name: {{ .Values.artiRepo.integration }}
          inputSteps:
            - name: npm_build_step
          outputResources:
            - name: npm_buildinfo
